name: "example oidc"
on:
  push:
    branches:
      - "master"
jobs:
  run:
    name: "example to list bucket contents"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
      - name: Docker
        run: |
          docker pull nginx:1.21.6
          docker tag nginx:1.21.6 eu.gcr.io/anna-money/custom-nginx-delete:1.21.6
          docker push eu.gcr.io/anna-money/custom-nginx-delete:1.21.6
