name: "Example Workload Identity"
on:
  push:
    branches:
      - "master"
jobs:
  run:
    name: "Example push to ANNA Money Docker registry via WorkloadIdentity auth"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: "Auth in GCP"
        id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
      - name: "Docker login"
        run: |
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
      - name: "Docker pull, tag and push"
        run: |
          docker pull nginx:1.21.6
          docker tag nginx:1.21.6 eu.gcr.io/anna-money/custom-nginx-delete:1.21.6
          docker push eu.gcr.io/anna-money/custom-nginx-delete:1.21.6
